export const CHANGE_FORM_OPEN = 'CHANGE_FORM_OPEN';
export const GET_DATA_INGREDIENT = 'GET_DATA_INGREDIENT';
export const FETCH_DATA = "FETCH_DATA";
export const FETCH_ERROR = "FETCH_ERROR";
export const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS";
export const ADD_DATA_ERROR = "ADD_DARA_ERROR";